# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NvdbBetaProduction
                                 A QGIS plugin
 nvdb plugin to filtrate and show objects belonging to the norwegian roads
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-12
        copyright            : (C) 2023 by SVV
        email                : alexander.casado@vegvesen.no
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NvdbBetaProduction class from file NvdbBetaProduction.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nvdb_beta import NvdbBetaProduction
    return NvdbBetaProduction(iface)
