# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'more_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoreDialog(object):
    def setupUi(self, MoreDialog):
        MoreDialog.setObjectName("MoreDialog")
        MoreDialog.resize(581, 553)
        self.more_main_tab = QtWidgets.QTabWidget(MoreDialog)
        self.more_main_tab.setGeometry(QtCore.QRect(10, 0, 561, 481))
        self.more_main_tab.setObjectName("more_main_tab")
        self.location_tab = QtWidgets.QWidget()
        self.location_tab.setObjectName("location_tab")
        self.more_main_tab.addTab(self.location_tab, "")
        self.relation_tab = QtWidgets.QWidget()
        self.relation_tab.setObjectName("relation_tab")
        self.more_main_tab.addTab(self.relation_tab, "")

        self.retranslateUi(MoreDialog)
        self.more_main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MoreDialog)

    def retranslateUi(self, MoreDialog):
        _translate = QtCore.QCoreApplication.translate
        MoreDialog.setWindowTitle(_translate("MoreDialog", "Mer"))
        self.more_main_tab.setTabText(self.more_main_tab.indexOf(self.location_tab), _translate("MoreDialog", "Stedfesting"))
        self.more_main_tab.setTabText(self.more_main_tab.indexOf(self.relation_tab), _translate("MoreDialog", "Kobling"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MoreDialog = QtWidgets.QDialog()
    ui = Ui_MoreDialog()
    ui.setupUi(MoreDialog)
    MoreDialog.show()
    sys.exit(app.exec_())
